/**
 * Shared fixtures for ViolationIntake tests.
 *
 * MOCK_INTAKE_QUESTIONS is the byte-exact body of the live endpoint —
 * generated by running app/services/violation_intake_steps.build_wizard_steps
 * over forms/san-diego-violation/form-config.json. Do NOT hand-edit it:
 * the previous hand-written mock encoded a shape the real API never
 * returned, which is exactly how the L5 blank-screen crash shipped.
 */

/** GET /violations/intake-questions response */
export const MOCK_INTAKE_QUESTIONS = {
  questions: {
    step1: {
      step_number: 1,
      step_name: 'Order & Urgency',
      description: 'Tell us which court order was violated and whether this is an emergency.',
      questions: [
        {
          id: 'violationType',
          type: 'select',
          label: 'What type of court order was violated?',
          required: true,
          options: [
            'Custody/Visitation',
            'Child Support',
            'Spousal Support',
            'Property Division',
            'Restraining Order',
            'Other Court Order',
          ],
        },
        {
          id: 'urgency',
          type: 'radio',
          label: 'Is this an emergency requiring immediate court action?',
          required: true,
          options: ['Yes', 'No'],
        },
      ],
    },
    step2: {
      step_number: 2,
      step_name: 'What Happened',
      description: 'Describe the violation and the evidence you have.',
      questions: [
        {
          id: 'violationDates',
          type: 'text',
          label: 'When did the violation(s) occur?',
          required: true,
          help_text: 'List each date separated by commas (e.g. 2026-06-06, 2026-06-13).',
        },
        {
          id: 'violationDescription',
          type: 'textarea',
          label: 'Describe what happened in detail',
          required: true,
        },
        {
          id: 'evidence',
          type: 'checkbox',
          label: 'What evidence do you have of the violation?',
          required: false,
          options: [
            'Text messages',
            'Emails',
            'Photos/Videos',
            'Witness statements',
            'Police reports',
            'Financial records',
            'Other documents',
          ],
        },
      ],
    },
    step3: {
      step_number: 3,
      step_name: 'Resolution & Requested Relief',
      description: 'Tell us about resolution attempts, prior violations, and what you want the court to do.',
      questions: [
        {
          id: 'attemptedResolution',
          type: 'radio',
          label: 'Have you attempted to resolve this without court intervention?',
          required: false,
          options: ['Yes', 'No'],
        },
        {
          id: 'resolutionDescription',
          type: 'textarea',
          label: 'Describe your attempts to resolve the issue',
          required: false,
          help_text: 'Only needed if you answered Yes above.',
        },
        {
          id: 'priorViolations',
          type: 'radio',
          label: 'Have there been prior violations by this party?',
          required: false,
          options: ['Yes', 'No'],
        },
        {
          id: 'priorViolationsDescription',
          type: 'textarea',
          label: 'Describe prior violations and any court actions taken',
          required: false,
          help_text: 'Only needed if you answered Yes above.',
        },
        {
          id: 'requestedRelief',
          type: 'checkbox',
          label: 'What do you want the court to do?',
          required: true,
          options: [
            'Modify custody/visitation',
            'Enforce support payments',
            'Find party in contempt',
            'Order makeup visitation',
            'Award attorney fees',
            'Issue sanctions/fines',
            'Modify existing orders',
            'Other relief',
          ],
        },
      ],
    },
  },
};

/** GET /violations/tracks response */
export const MOCK_TRACKS = {
  tracks: [
    {
      id: 'emergency',
      name: 'Emergency (Ex Parte)',
      timeline: '24-48 hours',
      description: 'For situations requiring immediate court intervention.',
      proofStandard: 'Preponderance of evidence',
      requiredForms: ['FL-300', 'FL-303', 'MC-030'],
    },
    {
      id: 'regular',
      name: 'Regular RFO',
      timeline: '3-6 weeks',
      description: 'Standard enforcement for non-emergency violations.',
      proofStandard: 'Preponderance of evidence',
      requiredForms: ['FL-300', 'MC-030'],
    },
    {
      id: 'contempt',
      name: 'Contempt of Court',
      timeline: '4-8 weeks',
      description: 'Quasi-criminal proceeding; higher proof standard applies.',
      proofStandard: 'Beyond reasonable doubt',
      requiredForms: ['FL-410', 'FL-411', 'MC-030'],
    },
  ],
  courthouses: [],
};

/** POST /violations/process response */
export const MOCK_PROCESS_RESULT = {
  success: true,
  track: 'regular',
  trackName: 'Regular RFO',
  timeline: '3-6 weeks',
  forms: [
    {
      id: 'FL-300',
      name: 'Request for Order',
      description: 'Main RFO form',
      fileName: 'fl300.pdf',
      required: true,
    },
    {
      id: 'MC-030',
      name: 'Declaration',
      description: 'Your declaration',
      fileName: 'mc030.pdf',
      required: true,
    },
  ],
  declaration: 'DECLARATION IN SUPPORT OF REQUEST FOR ORDER\n\nI declare...',
  courthouse: {
    name: 'San Diego Family Court',
    address: '1555 6th Ave, San Diego, CA 92101',
    phone: '(619) 450-7250',
  },
  instructions: [
    '1. Complete all required forms',
    '2. Make 3 copies of all documents',
  ],
  filingFee: '$60.00',
  serviceRequirements: {
    method: 'Mail or personal service',
    deadline: '5 days before hearing',
  },
};
